services:
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - frontend_backend
  frontend:
    container_name: frontend
    build:
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    networks:
      - frontend_backend
    depends_on:
      - backend
networks:
  frontend_backend:
    driver: bridge
