services:
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - frontback
  frontend:
    container_name: frontend
    build:
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    networks:
      - frontback
    depends_on:
      - backend
networks:
  frontback:
    driver: bridge
